package org.torproject.onionoo.updater;

enum DescriptorHistory {
  RELAY_CONSENSUS_HISTORY,
  RELAY_SERVER_HISTORY,
  RELAY_EXTRAINFO_HISTORY,
  EXIT_LIST_HISTORY,
  BRIDGE_STATUS_HISTORY,
  BRIDGE_SERVER_HISTORY,
  BRIDGE_EXTRAINFO_HISTORY,
}

